CREATE TABLE TB_LOGIN(
LG_ID SERIAL NOT NULL,
LG_USUARIO VARCHAR(30) NOT NULL,
LG_SENHA VARCHAR (32) NOT NULL,
PRIMARY KEY (LG_ID)
);

CREATE TABLE TB_USUARIOS(
USU_ID SERIAL NOT NULL PRIMARY KEY,
USU_NOME VARCHAR(70) NOT NULL,
USU_IDADE INT NOT NULL,  
USU_TELEFONE VARCHAR (20) NOT NULL,
USU_DATA_CADASTRO TIMESTAMP NOT NULL,  
USU_LG_ID INTEGER REFERENCES  TB_LOGIN(LG_ID)     
);


CREATE TABLE TB_TAREFAS(
TR_ID SERIAL NOT NULL PRIMARY KEY,
TR_TITULO VARCHAR(70) NOT NULL,
TR_TAREFA VARCHAR (500) NOT NULL,
TR_DATA_CADASTRO TIMESTAMP NOT NULL,
TR_LOG TIMESTAMP NOT NULL,   
TR_USU_ID INTEGER REFERENCES TB_USUARIOS(USU_ID)   
);


CREATE OR REPLACE FUNCTION MD5_SENHA() RETURNS TRIGGER AS $$
BEGIN 
    NEW.LG_SENHA = MD5(NEW.LG_SENHA);
    RETURN NEW;
END
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER CRIPTOGRAFA_SENHA 
BEFORE INSERT ON TB_LOGIN
FOR EACH ROW 
EXECUTE FUNCTION MD5_SENHA();

